### ISSUE TITLE
Consider implementing Ord

### ISSUE THREAD

**Issue by 1011X** [1011X/floating_bar#6]
It may be possible to have a sensible implementation of `Ord` for floating-bar numbers.

Unlike `float-ord` whose implementation violates the rule that `Ord` *must* agree with `Eq` (`-0` is considered less than `+0`, but `Eq` considers them equal), floating-bar has no concept of negative zero and won't run into this problem.

The most straight-forward way of ordering NaNs would be to first order by denominator size (since there's a range of denominator sizes that are invalid), and then order by their payload. All NaNs would also have to compare higher than all valid values in order to keep NaNs contiguous and separate from valid values when sorting.

Worth noting that the `NAN` constant provided by the library would always be the "highest" NaN value.

**Comment by 1011X** [comment]
Turns out that in order to allow for this, NaNs with different payloads would have to compare unequal. Otherwise, `Ord` would disagree with `Eq`. However, this would go counter to the idea of "fixing" NaNs by allowing any 2 of them to compare equal to each other, making something like `.is_nan()` necessary and thus defeating the point.

I think sticking to "all NaNs must compare equal" would be misguided. I'd prefer implementing `Ord`, having `.is_nan()` to test for valid values, and documenting the behavior of `==` for NaNs.

**Comment by JulianKnodt** [comment]
Just wanted to check about this, it seems that the conclusion was that `Ord` should be implemented and `NaNs` comparing equal is bad, but the current version doesn't seem to have this. Is this still something that should be implemented?
